stages:
    - build
    - upload
    - release

variables:
    PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/mavlink/${CI_COMMIT_TAG}/"
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    DIALECT_NAME: "oblot"

build_main:
    stage: build
    image: python:latest
    script:
        - apt-get update && apt-get -y install zip
        - python -V
        - pip install virtualenv
        - virtualenv venv
        - source venv/bin/activate
        - pip install future lxml
        - mkdir repos
        - cd repos
        - git clone https://github.com/mavlink/mavlink.git --recursive
        - export PYTHONPATH=${PWD}/mavlink
        - cd ..
        - mkdir output
        - python -m pymavlink.tools.mavgen -o ./output/${DIALECT_NAME}.py --lang=Python --wire-protocol=2.0 --strict-units mavlink/message_definitions/v2.0/oblot.xml
        - python -m pymavlink.tools.mavgen -o ./output/include/mavlink --lang=C --wire-protocol=2.0 --strict-units mavlink/message_definitions/v2.0/oblot.xml
        - cd output # to have correct paths in zip
        - zip -r mavlink-${DIALECT_NAME}.zip include/
    cache:
        paths:
            - .cache/pip
            - venv/
    artifacts:
        paths:
            - output/*.py
            - output/*.zip

upload:
    stage: upload
    image: curlimages/curl:latest
    rules:
        - if: $CI_COMMIT_TAG
    script:
        - |
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file output/${DIALECT_NAME}.py ${PACKAGE_REGISTRY_URL}
        - |
            curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file output/mavlink-${DIALECT_NAME}.zip ${PACKAGE_REGISTRY_URL}

release:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli:v0.4.0
    rules:
        - if: $CI_COMMIT_TAG
    script:
        - |
          release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
            --description "Automatic release for version ${CI_COMMIT_TAG}" \
            --assets-link "{\"name\":\"${DIALECT_NAME}.py\",\"url\":\"${PACKAGE_REGISTRY_URL}${DIALECT_NAME}.py\"}" \
            --assets-link "{\"name\":\"mavlink-${DIALECT_NAME}.zip\",\"url\":\"${PACKAGE_REGISTRY_URL}mavlink-${DIALECT_NAME}.zip\"}" \
